{
  "openapi": "3.0.1",
  "info": {
    "title": "EWM Comments feature API",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:9090",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "Private: Comments",
      "description": "API для работы с комментариями"
    },
    {
      "description": "Публичный API для работы с комментариями событий",
      "name": "Public: Comments"
    }
  ],
  "paths": {
    "/events/{eventId}/comment": {
      "post": {
        "tags": [
          "Private: Comments"
        ],
        "summary": "Сохранение информации о том, что к эндпоинту был запрос",
        "description": "Отзыв относится к одному событию, а вот событие может иметь много комментариев\n- Отзыв может оставить только тот пользователь, который посещал это событие в аренду\n- Отзыв может оставить  только после окончания срока аренды",
        "operationId": "/events/{eventId}/comment",
        "requestBody": {
          "description": "данные запроса",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewCommentRequestDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Информация сохранена"
          }
        }
      }
    },
    "/comments": {
      "get": {
        "description": "В случае, если по заданным фильтрам не найдено ни одной комментарии, возвращает пустой список",
        "operationId": "getComments",
        "parameters": [
          {
            "description": "количество комментарий, которые нужно пропустить для формирования текущего набора",
            "in": "query",
            "name": "from",
            "required": false,
            "schema": {
              "minimum": 0,
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "description": "количество комментарий в наборе",
            "in": "query",
            "name": "size",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommentResponseDto"
                  }
                }
              }
            },
            "description": "комментарии найдены"
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type int; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Запрос составлен некорректно"
          }
        },
        "summary": "Получение комментарий",
        "tags": [
          "Public: Comments"
        ]
      }
    },
    "/comments/{eventId}": {
      "get": {
        "description": "В случае, если события с заданным id не найдено, возвращает статус код 404",
        "operationId": "getComment",
        "parameters": [
          {
            "description": "id комментарии",
            "in": "path",
            "name": "catId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentResponseDto"
                }
              }
            },
            "description": "комментария найдена"
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Запрос составлен некорректно"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Category with id=19 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "комментария не найдена или недоступна"
          }
        },
        "summary": "Получение информации о комментарии по её идентификатору",
        "tags": [
          "Public: Comments"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "NewCommentRequestDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Идентификатор комментария",
            "format": "int64",
            "readOnly": true,
            "example": 1
          },
          "text": {
            "type": "string",
            "description": "Содержимое комментария",
            "example": "Содержимое комментария"
          },
          "item": {
            "type": "string",
            "description": "событие, к которому относится комментарий;",
            "readOnly": true,
            "example": "событие"
          },
          "authorName": {
            "type": "string",
            "description": "автор комментария",
            "example": "автор комментария"
          },
          "created": {
            "type": "string",
            "description": "Дата и время, когда был совершен запрос к эндпоинту (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-09-06 11:00:23"
          }
        }
      },
      "CommentResponseDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Идентификатор комментария",
            "format": "int64",
            "readOnly": true,
            "example": 1
          },
          "text": {
            "type": "string",
            "description": "Содержимое комментария",
            "example": "Содержимое комментария"
          },
          "item": {
            "type": "string",
            "description": "событие, к которому относится комментарий;",
            "readOnly": true,
            "example": "событие"
          },
          "authorName": {
            "type": "string",
            "description": "автор комментария",
            "example": "автор комментария"
          },
          "created": {
            "type": "string",
            "description": "Дата и время, когда был совершен запрос к эндпоинту (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-09-06 11:00:23"
          }
        }
      }
    }
  }
}
